### PR TITLE
First pipeline updates

### PR DESCRIPTION
**Pull request by blohre-usgs**
@skybristol ,

Here are my initial changes to get your code running the pipeline. A brief outline of my changes and code are below. Let me know if you have any questions, things don't make sense, or we need to reconsider some architectural solutions. I expect we'll need to make changes so let me know where those might be. For now we're just processing the first 6 files to test things out.

Some questions:
* Is there a json schema to validate against for the final expected product? I assumed the final sgcn data is what ends up in the `sgcn.sgcn` sqlite table, let me know if that's wrong. On initial insert into the table we check against the `resources/sgcn_source_records_schema.json` file but we don't check against a json schema before updating that table in `Infuse Taxonomic Summary.ipynb`
* A lot of the data gathered by pySppIn isn't added back into the summary data. Is it correct to assume that the data gathered from ECOS, GBIF, IUCN, and NatureServe will need to be provided in the final api? Would we also include direct access to ITIS and/or WoRMS data collected in the api?

## Overall structure
I started by trying to understand and run the jupyter notebook files you had for processing. Those steps have more or less been inserted/translated into the `bis_pipeline.py` file. I've added comments to make it more obvious what code cooresponds to a specific notebook script.

I followed the general architecture design we created for the other processes we've added into the pipeline. It's explained here: https://code.chs.usgs.gov/fort/bcb/pipeline/docs (let me know if you can't access that repo).

#### `process_sppin_source_search_term`
The biggest changes revolved around the `process_sppin_source_search_term` method. It was closely coupled with your sql messaging and caching system so I broke it out into multiple methods at the bottom of `sgcn.py` so it could be run in the pipeline.
#### `check_historic_list` and `check_itis_override`
These methods can now operate on a provided metadata dictionary. In the pipeline environment external scripts don't have direct access to the local disk. This functionality was added to keep as much of the code as possible in the external repo. We could also download and store these metadata files outside of the external code and provide a path to the file through the `path` variable to `process_n` methods.

#### `process_sgcn_source_item`
I noticed that quite a few rows were failing on the json schema validation step because their value was `NaN`, which is invalid json. It was a product of the pandas `read_csv` step converting empty strings, `""`, to `NaN`. 2 lines of code were added to this method to address that issue for `common name` and `taxonomic category`. It still fails for blank `scientific name`s

## Caching
Before this process, external scripts didn't have direct access to our permanent infastructure. The SGCN scripts have created the necessity for direct access to some sort of cache. My idea for the simpliest and most generic solution was to create a `CacheManager` class with a simple api for these interactions. There are 2 methods:
```
`get_from_cache(key)`, takes a `string` key and returns a value if present or `None`
`add_to_cache(key, value)`, takes a `string` key and a dictionary `value`. 
This method replaces the existing `value` for `key` if it exists and otherwise creates a new record. `None` is returned on success otherwise the `Error` is returned
```
The functionality is simple for now to get the pipeline running in AWS. What additional functionality do you think we'll need for caching? The first thing that comes to mind is expiration dates. Would we also need cache history independent of the pipeline data itself? (We can currently store what information was used to create a piece of data but it is specifically tied to that data result.)

## Running locally
I've created a local "pipeline" so that processing can be tested locally. It uses sqlite for permanent infastructure so you have an idea of what values will be once stored in AWS. Just modify the `cache_root` variable in `local_pipeline_run.py` to point towards a local sqlite db. Run it with `python local_pipeline_run.py`

### CODE REVIEW

**Comment by skybristol** [comment]
Most of this makes a lot of sense. I appreciate the work you’ve put into thinking this through in terms of how the workflow steps would operate in the type of pipeline environment we are creating.

The pySppIn package is being set up to serve many different purposes for species information gathering. Any given case like SGCN will make decisions on what’s needed from what that package retrieves. In this case, I think I just focused mostly on what SGCN is already using, which is not everything from those sources. Over time, of course, this is all going to change, and we will need to develop some better design patterns for dealing with that change and introducing new and different data for these kinds of systems over time. Each application will need to work out what its requirements are for backwards compatibility and data versioning. Some will just want the latest of everything while others will care about keeping different versions of specific properties as well as whole data structures. We have an important case in point we need to deal with right now, in fact, where the whole FWS ECOS/TESS thing needs to [completely change](https://github.com/skybristol/notebooks/blob/master/New%20ECOS%20REST%20service.ipynb) to work with a whole new REST service.

One area that does maybe need a little clarification is the stuff on the historic list and ITIS overrides. I set those up to operate against files stored in ScienceBase retrieved via HTTP, not against local disc. The point there is to keep everything together in terms of the “source data management regime.” I’ve used this pattern in other use cases where we put keep all the stuff that the originating data manager needs to work up and configure together there in ScienceBase through a combination of ScienceBase Item metadata and “attached” file content. That keeps everything within that entity’s control without introducing anything else into the mix that needs to be maintained in terms of permissions and whatever else is involved. As long as the “metadata dictionary” is derived from what’s stored in ScienceBase and there is something built into the process to go check the source for updates, that should be fine.

I’m not completely sure what you mean by “external scripts.” It seems like we would configure whatever the system needs to connect to and how to connect in terms of checking on existing data into some kind of environment variable construct. If it’s a closed environment, then those parameters will be set up for that space and control whatever access is needed. What am I missing?

**Comment by blohre-usgs** [comment]
Re: pySppIn
Makes sense, I think we have a good start on this and can address/update the pipeline side as needs arise. Our versioning and data change documentation is much more robust for what I'm calling "final data" than for the cached items but we can use a lot of that functionality for the cache as well. Should I generate a final json schema based on what ends up in `sgcn.sgcn`? Or do you have one we could check against?

I confused myself a bit on the historic list and ITIS overrides. We're still pulling that data directly from SB. Originally the process stored in the sqlite (not local disk) to be queried later. Now we pull that info from SB and pass the parsed "metadata_cache" dictionary to the necessary steps.

"External scripts" just refers to processes outside of our pipeline code like this repo. Hopefully that clears things up. Right now the pattern is for all data interactions with the pipeline to be managed through methods or classes we pass as arguments to the `process_n` methods.

**Comment by blohre-usgs** [comment]
Converted this PR to a draft because attempting to process all of the SB files results in the first processing lambda timing out. For simplicity's sake we parsed the data from SB files in one lambda but I'm going to break it into multiple lambdas to run in parallel, similar to the original notebook scripts.

**Comment by blohre-usgs** [comment]
I successfully completed the first full run of the pipeline in AWS. Once merged I can switch the pipeline over to using this repository for processing.

**Comment by skybristol** [comment]
Thanks for all the work on this, @blohre-usgs. What you put in place makes good sense.

I am routinely frustrated by the variety of issues that make real time stable processing of files in the ScienceBase Repository next to impossible. Trying to sling data around over HTTP is always suboptimal, but various issues with what we often call the DOI security gauntlet that every HTTP request has to go through make it really bad. As soon as we can get the new sbFiles stuff in place that Allen, Tekell, and the group have been working on, we should be able to shift all of our data files to ScienceBase's S3 bucket(s). From there, we can completely rethink things in terms of triggering lambda processes and how versioning should impact these data gatherers. We may still have to get back for metadata via the ScienceBase API, but we at least can have our file content somewhere for easier processing.

**Pull request merged**
